# GitHub Actions Workflow (.github/workflows/deploy.yml)
name: Deploy Application

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run system checks    # ← YOUR SCRIPT HERE!
        run: |
          chmod +x mini_project1_system_info.sh
          ./mini_project1_system_info.sh 
          cat system_report*.txt
      - name: Build and Deploy      # ← SHELL SCRIPTING!
        run: |
          docker build -t myapp .
          
